/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#004d57",
        "surface": "#0a0e14",
         "on-error-container": "#ffa8a3",
              "secondary-dim": "#7e51ff",
              "surface-bright": "#262c36",
              "surface-container": "#151a21",
              "error-dim": "#d7383b",
              "surface-variant": "#20262f",
              "surface-container-low": "#0f141a",
              "background": "#0a0e14",
              "on-secondary": "#25006b",
              "tertiary": "#81ecff",
              "on-tertiary-fixed": "#003840",
              "on-secondary-container": "#e4daff",
              "tertiary-fixed-dim": "#00d4ec",
              "secondary-fixed-dim": "#cabaff",
              "secondary": "#a68cff",
              "on-tertiary": "#005762",
              "on-secondary-fixed-variant": "#591bdc",
              "on-surface-variant": "#a8abb3",
              "on-surface": "#f1f3fc",
              "surface-dim": "#0a0e14",
              "on-background": "#f1f3fc",
              "on-primary-container": "#002344",
              "inverse-on-surface": "#51555c",
              "primary-fixed-dim": "#4899f1",
              "on-secondary-fixed": "#3b00a0",
              "on-tertiary-fixed-variant": "#005762",
              "surface-container-highest": "#20262f",
              "tertiary-fixed": "#00e3fd",
              "primary": "#72b1ff",
              "error": "#ff716c",
              "primary-container": "#55a3fc",
              "on-primary": "#002f58",
              "outline-variant": "#44484f",
              "secondary-container": "#591adc",
              "surface-container-high": "#1b2028",
              "secondary-fixed": "#d8caff",
              "on-error": "#490006",
              "tertiary-container": "#00e3fd",
              "error-container": "#9f0519",
              "primary-dim": "#52a1f9",
              "inverse-surface": "#f8f9ff",
              "surface-tint": "#72b1ff",
              "on-primary-fixed-variant": "#002f58",
              "primary-fixed": "#58a6ff",
              "outline": "#72757d",
              "tertiary-dim": "#00d4ec",
              "surface-container-lowest": "#000000",
              "inverse-primary": "#0061ab",
              "on-primary-fixed": "#000002"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Fira Code"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}